[book]
title = "x86-64 Simplified"
author = "Thomas Lindae"
language = "en"
multilingual = false
src = "src"

[build]
# create-missing = false
use-default-preprocessors = false

[output.html]
default-theme = "ayu"
git-repository-url = "https://github.com/Treeniks/x86-64-simplified"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[preprocessor.links]

[preprocessor.svgbob2]

[preprocessor.katex]
